# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BindConfigACL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='子网')),
                ('acl_name', models.CharField(choices=[('devsubnet', '研发环境网络'), ('sitsubnet', 'sit测试环境网络'), ('uatsubnet', 'uat测试环境网络'), ('prosubnet', '生产环境网络')], default='devsubnet', max_length=32, verbose_name='子网分组')),
                ('resolv_area', models.CharField(choices=[('internal', '内网解析')], default='internal', max_length=32, verbose_name='解析区域')),
                ('description', models.CharField(default='', max_length=512, verbose_name='描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('is_applied', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已应用')),
                ('is_deleted', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已删除')),
            ],
        ),
        migrations.CreateModel(
            name='BindConfigView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='view名称')),
                ('acl_name', models.CharField(choices=[('devsubnet', '研发环境网络'), ('sitsubnet', 'sit测试环境网络'), ('uatsubnet', 'uat测试环境网络'), ('prosubnet', '生产环境网络')], default='devsubnet', max_length=32, verbose_name='acl引用')),
                ('allowed_key', models.CharField(default='dev-key', max_length=16, verbose_name='key配置')),
                ('description', models.CharField(default='', max_length=512, verbose_name='描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('is_applied', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已应用')),
                ('is_deleted', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已删除')),
            ],
        ),
        migrations.CreateModel(
            name='BindConfigZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='域名')),
                ('zone_type', models.CharField(choices=[('inner_domain', '内网域名'), ('outer_domain', '公网域名')], default='inner_domain', max_length=16, verbose_name='域名类型')),
                ('description', models.CharField(default='', max_length=512, verbose_name='描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('is_deleted', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已删除')),
            ],
        ),
        migrations.CreateModel(
            name='BindNSRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='解析名称')),
                ('record_type', models.CharField(choices=[('A', 'A记录'), ('AAAA', '4A记录'), ('CNAME', 'CNAME'), ('MX', 'MX记录')], default='devsubnet', max_length=32, verbose_name='记录类型')),
                ('resolv_addr', models.CharField(default='', max_length=64, verbose_name='解析地址')),
                ('ttl_seconds', models.IntegerField(choices=[(600, '10 min'), (3600, '1 hour'), (86400, '1 day')], default=600, verbose_name='TTL设置')),
                ('description', models.CharField(default='', max_length=512, verbose_name='描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('is_applied', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已应用')),
                ('is_disabled', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已失效')),
                ('is_deleted', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已删除')),
                ('view_belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containing_records', to='dns.BindConfigView')),
                ('zone_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containing_records', to='dns.BindConfigZone')),
            ],
        ),
    ]
