# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0002_bindconfigacl_bindconfigview_bindconfigzone_bindnsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindconfigview',
            name='readable_name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='别名'),
        ),
    ]
