# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0004_bindfileregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindfileregister',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
    ]
