# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0005_bindfileregister_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bindconfigacl',
            name='resolv_area',
        ),
        migrations.AlterField(
            model_name='bindnsrecord',
            name='record_type',
            field=models.CharField(choices=[('A', 'A记录'), ('AAAA', '4A记录'), ('CNAME', 'CNAME'), ('MX', 'MX记录'), ('NS', 'NS记录')], default='devsubnet', max_length=32, verbose_name='记录类型'),
        ),
    ]
