# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0007_auto_20171114_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindnsrecord',
            name='uuid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='唯一标识'),
        ),
    ]
