# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0008_bindnsrecord_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiClustersDataSyncCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_synctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次同步时间')),
                ('data_content', models.CharField(default='', max_length=512, verbose_name='数据内容')),
                ('failed_cluster', models.CharField(choices=[('cluster2', '测试集群2'), ('cluster1', '测试集群1'), ('ALL', '所有集群')], default='', max_length=32, verbose_name='集群名称')),
                ('sync_url', models.CharField(default='', max_length=128, verbose_name='请求域名')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重新同步次数')),
            ],
        ),
        migrations.AlterField(
            model_name='bindconfigacl',
            name='cluster_name',
            field=models.CharField(choices=[('cluster2', '测试集群2'), ('cluster1', '测试集群1'), ('ALL', '所有集群')], default='', max_length=32, verbose_name='集群名称'),
        ),
        migrations.AlterField(
            model_name='bindconfigview',
            name='cluster_name',
            field=models.CharField(choices=[('cluster2', '测试集群2'), ('cluster1', '测试集群1'), ('ALL', '所有集群')], default='', max_length=32, verbose_name='集群名称'),
        ),
        migrations.AlterField(
            model_name='bindnsrecord',
            name='cluster_name',
            field=models.CharField(choices=[('cluster2', '测试集群2'), ('cluster1', '测试集群1'), ('ALL', '所有集群')], default='', max_length=32, verbose_name='集群名称'),
        ),
    ]
