# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0009_auto_20171128_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiclustersdatasynccache',
            name='is_synced',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已成功推送'),
        ),
    ]
